name: MLflow CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Miniconda
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
        auto-update-conda: true
        activate-environment: weather_env
        environment-file: MLProject/conda.yaml

    # Prepare environment
    - name: Create or Update Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
        auto-update-conda: true
        activate-environment: weather_env
        environment-file: MLProject/conda.yaml

    - name: Create or Update Environment
      run: |
        cd MLProject
        conda env update -n weather_env -f conda.yaml || conda env create -n weather_env -f conda.yaml

    # Run MLflow Project
    - name: Run MLflow project
      run: |
        cd MLProject
        conda run -n weather_env mlflow run .

    # Upload MLflow Artifacts
    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns/
