name: MLflow CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"

    - name: Create environment from conda.yaml
      run: |
        cd MLProject
        conda env create -f conda.yaml -n weather_env || conda env update -f conda.yaml -n weather_env
        conda init bash
        source ~/.bashrc

    - name: Run MLflow Project
      run: |
        cd MLProject
        conda activate weather_env
        mlflow run .
